### ISSUE TITLE
distinct_id in the wrong format

### ISSUE THREAD

**Issue by mbrucki** [stape-io/mixpanel-tag#7]
Hi,

currently, the `distinct_id` set by Stape's library doesn't follow the Mixpanel guidelines regarding merging profiles. It should be in the UUID v4 format to be merged at the `create-identity` call. 

![Screenshot 2024-08-08 at 12 44 42](https://github.com/user-attachments/assets/ed11f6d4-3424-4e80-9d7d-2eb26bc8469a)

Please find the full Mixpanel documentation [here](https://developer.mixpanel.com/reference/create-identity). 

Thank you for your attention to this matter.

All the best,
Mariusz

**Comment by Bukashk0zzz** [comment]
Hi, 

We added this issue to our backlog.

**Comment by Bukashk0zzz** [comment]
Fixed
